FROM scratch

ADD lfs-mkpod.tar.gz    /
COPY passwd             /etc/passwd
COPY group              /etc/group
COPY macros.lfs         /usr/lib/rpm/macros.d/macros.lfs

RUN install -o 1000 -g 1000 -d /build/rpmbuild && \
    rpm -i --justdb --nodeps /root/*.rpm

WORKDIR /build

CMD [ "/usr/bin/tail", "-f", "/dev/null" ]
