FROM scratch

ADD lfs-mkpod.tar.gz    /

RUN mkdir -p /etc/yum.repos.d

COPY passwd             /etc/passwd
COPY group              /etc/group
COPY macros.pod         /usr/lib/rpm/macros.d/macros.pod
COPY pod.repo           /etc/yum.repos.d/pod.repo

RUN install -o 1000 -g 1000 -d /rpmbuild && \
    rpm -i --justdb --nodeps /root/*.rpm

# localedef needed for perl to compile
RUN mkdir /usr/lib/locale && \
    /usr/bin/localedef -i POSIX -f UTF-8 C.UTF-8 || true

RUN dnf update -y
RUN rm -rf /root/*.rpm

WORKDIR /rpmbuild

CMD [ "/usr/bin/tail", "-f", "/dev/null" ]
