#!/bin/bash

set -a

export lfs_host_image=fedora:42
export lfs_version=12.4~rc1
export lfs_url_version=12.4-rc1
export lfs_vendor=lfs
export lfs_root_size=10G
export lfs_init_user=${lfs_vendor}

export lfs_dir=/${lfs_vendor}
export lfs_tools_dir=${lfs_dir}/tools
export lfs_tgt=x86_64-${lfs_vendor}-linux-gnu
export lfs_root_img=build/${lfs_vendor}-${lfs_version}-root.img
export lfs_install_dir=/var/lib/libvirt/images

lfs_version_1=$(echo $lfs_version | cut -f1 -d.)
lfs_dist=.lfs${lfs_version//./_}

export lfs_version_1 lfs_dist

if [ -e local-lfs.env ] ; then
    . ./local-lfs.env
fi
