#!/bin/bash

set -e

prog="$(basename $0)"
cd "$(dirname $0)"

source ./pod-env

rpmbuild_flags=""
rpmspec_flags=(--define "dist ${pod_dist}")

usage() {
    cat <<EOF

Usage: $prog <command> [args...]

EOF
    exit 2
}

usage-export() {
    cat <<EOF

Usage: $prog export <package_list.txt>

EOF
    exit 2
}

pod-createrepo() {
    echo -n "creating repository... "
    mkdir -p        build/rpms/pod
    createrepo_c -q build/rpms/pod
    echo "done."
}

pod-init() {
    set -x

    pod-createrepo
    podman stop -t 0 lfs-pod    >/dev/null 2>&1  || true
    podman rmi --force lfs-pod  >/dev/null 2>&1  || true
    podman build \
        --tag       lfs-pod \
        --volume    "$(pwd)/build/rpms/pod:/rpmbuild/RPMS:z" \
        containers/lfs-pod
}

timestamp() {
    date +"%Y-%m-%d %H:%m:%S"
}

pod-build() {
    source=$1
    rebuild=$2
    package="$(basename $source)"
    spec="${package}.spec"

    package_arch=$(rpmspec "${rpmspec_flags[@]}" -q --queryformat="%{ARCH}"  "$source/$spec" | head -1)
    package_version=$(rpmspec "${rpmspec_flags[@]}" -qv "$source/$spec" | head -1 | sed 's/.src//')
    if [ -z "$rebuild" ] && [ -e "build/rpms/pod/packages/$package/${package_arch}/${package_version}.rpm" ] ; then
        echo "package already built: $package"
        return
    fi

    ./lfs download $source

    echo "pod:$package" > logs/last-started
    echo "[$(timestamp)] start pod:$package" >> logs/build.log
    echo -e "\n----- building pod:$package"

    mkdir -p        build/srpms
    mkdir -p        logs/pod

    pod-createrepo
    pod-create

    rm -rf  build/deps
    mkdir   build/deps

    podman exec \
        --user root \
        lfs-pod \
        dnf builddep -y \
        /host/$source/$spec

    rm -rf   "build/rpms/pod/packages/$package"
    mkdir -p "build/rpms/pod/packages/$package"

    echo "building $package"

    # make the sources directory by symlinking the needed parts
    rm -rf build/sources
    mkdir -p build/sources
    ( cd build/sources && \
        downloads=$(ls ../../downloads/$package)
        for download in $downloads; do
            ln -s ../../downloads/${package}/$download .
        done
        sources=$(ls ../../sources/$package)
        for source in $sources; do
            ln -s ../../sources/${package}/${source} .
        done
    )

    set -e -o pipefail
    podman exec \
        lfs-pod \
        rpmbuild \
            -ba --nocheck \
            --define "_topdir /rpmbuild" \
            --define "_sourcedir /host/build/sources" \
            --define "_rpmdir /rpmbuild/RPMS/packages/$package" \
            $rpmbuild_flags \
            /host/$source/$spec | \
            tee logs/pod/${package}.log

    echo "pod:$package" > logs/last-success
    echo "[$(timestamp)] done  pod:$package" >> logs/build.log

    echo "building repository"
    createrepo_c build/rpms/pod

    echo "ensuring package can be installed"
    # Ensure the newly built package can be installed
    podman exec --user root \
        lfs-pod \
        dnf install -y "$package" | \
    tee --append "logs/pod/${package}.log"

}

pod-export() {
    if [ -z $1 ] ; then
        echo "error: missing argument"
        usage-export
    fi

    packages=$(cat $1)

    pod-createrepo
    pod-init
    pod-create

    podman exec --user root lfs-pod \
        dnf install -y $packages
    image="build/containers/lfs-pod.tar.gz"
    echo -n "exporting ${image}... "
    podman exec --user root -t lfs-pod \
        tar -C / -c -z -f /host/$image \
            --exclude='./rpmbuild' \
            --exclude='./host' \
            --exclude='./tmp/*' \
            --exclude './dev/*' \
            --exclude './proc/*' \
            --exclude './sys/*' \
            .
    echo "done."
}

pod-create() {
    pod-destroy

    echo "creating container"
    bash -c "source ./pod-env ; env | grep -e '^pod_'" > eval-pod.env
    mkdir -p build/images

    podman create \
        --name      lfs-pod \
        --hostname  lfs-pod \
        --env-file  eval-pod.env \
        --userns    keep-id \
        --volume    "./build/rpms/pod:/rpmbuild/RPMS:z" \
        --volume    "./build/srpms:/rpmbuild/SRPMS:z" \
        --volume    .:/host:z \
        lfs-pod
    podman start lfs-pod
}

pod-destroy() {
    podman stop -t 0    lfs-pod || true
    podman rm -f        lfs-pod || true
}

case $1 in
    init)
        pod-init
        ;;
    create)
        pod-create
        ;;
    destroy)
        pod-destroy
        ;;
    build)
        shift
        echo "" >> logs/build.log
        sources=$(grep -v -e '^#' $1)
        for arg in $sources; do
            pod-build $arg
        done
        ;;
    export)
        shift
        pod-export $1
        ;;
    rpm)
        shift
        for arg in "$@" ; do
            pod-build $arg "rebuild"
        done
        ;;
    shell)
        exec podman exec -it lfs-pod /bin/bash
        ;;
    root)
        exec podman exec --user root -it lfs-pod /bin/bash
        ;;
    *)
        echo "$prog: error: invalid command" 1>&2
        usage
        ;;
esac

