FROM scratch

ADD lfs-stage2.tar.gz /

COPY passwd         /etc/passwd
COPY group          /etc/group
COPY passwd.root    /root
COPY passwd.user    /root

ARG  lfs_init_user

RUN cat /root/passwd.root /root/passwd.root /root/passwd.root | passwd root && \
    useradd --create-home ${lfs_init_user} && \
    cat /root/passwd.user /root/passwd.user /root/passwd.user | passwd ${lfs_init_user} && \
    rm -f /root/passwd.{root,user}

WORKDIR /home/${lfs_init_user}
USER ${lfs_init_user}

CMD [ "/usr/bin/tail", "-f", "/dev/null" ]