ARG  lfs_host_image
FROM ${lfs_host_image}

RUN dnf install -y \
    binutils \
    bison \
    cmake \
    diffutils \
    flex \
    gcc \
    g++ \
    gettext \
    less \
    nano \
    patch \
    perl \
    python \
    rpm-build \
    rpmdevtools \
    texinfo \
    xz

RUN ln -s /usr/bin/bison /usr/bin/yacc

COPY macros.lfs-stage   /etc/rpm/macros.lfs-stage
COPY macros.lfs-stage1  /etc/rpm/macros.lfs-stage1
COPY sudoers            /etc/sudoers.d/lfs

RUN install -d /var/lib/lfs-rpm && \
    install -d -m 755 -o 1000 -g 1000 /rpmbuild

RUN sed -i 's/%source_date_epoch_from_changelog 1/%source_date_epoch_from_changelog 0/' /usr/lib/rpm/redhat/macros && \
    sed -i 's/%_auto_set_build_flags 1//' /usr/lib/rpm/redhat/macros

WORKDIR /rpmbuild

CMD [ "tail", "-f", "/dev/null" ]
