ARG  lfs_host_image
FROM ${lfs_host_image}

RUN dnf install -y \
    binutils \
    bison \
    cmake \
    diffutils \
    flex \
    gcc \
    g++ \
    gettext \
    less \
    nano \
    patch \
    perl \
    python \
    rpm-build \
    rpmdevtools \
    texinfo \
    xz

RUN ln -s /usr/bin/bison /usr/bin/yacc

COPY macros.lfs         /usr/lib/rpm/macros.d/macros.lfs
COPY macros.lfs-stage   /usr/lib/rpm/macros.d/macros.lfs-stage
COPY sudoers            /etc/sudoers.d/lfs

RUN install -o 1000 -g 1000 -d /build/rpmbuild && \
    rm -rf /var/lib/rpm/*

RUN sed -i 's/%source_date_epoch_from_changelog 1/%source_date_epoch_from_changelog 0/' /usr/lib/rpm/redhat/macros && \
    sed -i 's/%_auto_set_build_flags 1//' /usr/lib/rpm/redhat/macros

WORKDIR /build

CMD [ "tail", "-f", "/dev/null" ]
