FROM scratch

ADD lfs-stage1.tar.gz /

COPY passwd /etc/passwd
COPY group /etc/group

RUN mkdir -p /home/lfs && \
    chown lfs:lfs /home/lfs

WORKDIR /home/lfs
USER lfs

ARG nproc
ENV MAKEFLAGS=-j${nproc} 

CMD [ "/usr/bin/tail", "-f", "/dev/null" ]
