Name:           findutils
Version:        4.9.0
Release:        1%{?dist}
Summary:        The GNU versions of find utilities (find and xargs)
License:        GPLv3+

Source0:        https://ftp.gnu.org/gnu/findutils/findutils-%{version}.tar.xz

%description
The findutils package contains programs which will help you locate files on
your system. The find utility searches through a hierarchy of directories
looking for files which match a certain set of criteria (such as a file name
pattern). The xargs utility builds and executes command lines from standard
input arguments (usually lists of file names generated by the find command).

You should install findutils because it includes tools that are very useful for
finding things on your system.

#---------------------------------------------------------------------------
%prep
%setup -q

#---------------------------------------------------------------------------
%build
%lfs_build_begin

%if %{with lfs_bootstrap}
./configure --prefix=/usr                   \
            --localstatedir=/var/lib/locate \
            --host=%{lfs_tgt}               \
            --build=$(build-aux/config.guess)

%else 
./configure --prefix=/usr --localstatedir=/var/lib/locate

%endif
%make
%lfs_build_end

#---------------------------------------------------------------------------
%install
%lfs_install_begin

%if %{with lfs_bootstrap}
%make DESTDIR=%{buildroot}/%{lfs_dir} install

%else 
make DESTDIR=%{buildroot} install

%endif
%lfs_install_end

#---------------------------------------------------------------------------
%check
make check

#---------------------------------------------------------------------------
%files
%if %{with lfs_bootstrap}
%{lfs_dir}/usr/bin/*
%{lfs_dir}/usr/libexec/*
%{lfs_dir}/usr/share/locale/*/LC_MESSAGES/findutils.mo

%else 
/usr/bin/find
/usr/bin/locate
/usr/bin/updatedb
/usr/bin/xargs
/usr/libexec/frcode
/usr/share/info/*
/usr/share/locale/*/LC_MESSAGES/findutils.mo
/usr/share/man/man{1,5}/*

%endif


