Name:           ninja
Version:        1.11.1
Release:        1%{?dist}
Summary:        Ninja is a small build system with a focus on speed
License:        ASL

Source0:        https://github.com/ninja-build/ninja/archive/v%{version}/ninja-%{version}.tar.gz

%description
Ninja is a small build system with a focus on speed. It differs from other
build systems in two major respects: it is designed to have its input files
generated by a higher-level build system, and it is designed to run builds as
fast as possible.

#---------------------------------------------------------------------------
%prep
%setup -q

#---------------------------------------------------------------------------
%build
%lfs_build_begin

python3 configure.py --bootstrap
%lfs_build_end

#---------------------------------------------------------------------------
%install
%lfs_install_begin

install -m 755 -d %{buildroot}/usr/bin
install -m 755 -d %{buildroot}/usr/share/bash-completion

install -vm755 ninja %{buildroot}/usr/bin
install -vDm644 misc/bash-completion %{buildroot}/usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  %{buildroot}/usr/share/zsh/site-functions/_ninja
%lfs_install_end

#---------------------------------------------------------------------------
%check
./ninja ninja_test
./ninja_test --gtest_filter=-SubprocessTest.SetWithLots

#---------------------------------------------------------------------------
%files
/usr/bin/ninja
/usr/share/bash-completion/completions/ninja
/usr/share/zsh/site-functions/_ninja